Final Project/finalproject/finalproject/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('flightfinder.urls', namespace='Flightfinder')),
    path('admin/', admin.site.urls),
]

Final Project/finalproject/flightfinder/urls.py
from django.urls import path

from . import views

app_name = 'flightfinder'

urlpatterns = [
    path('', views.index, name='index'),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path('origin_airport_search/', views.origin_airport_search, name='origin_airport_search'),
    path('flight_search', views.flight_search, name='flight_search'), 
]

Final Project/finalproject/flightfinder/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
import datetime

# Create your models here.
class User(AbstractUser):
    pass

class Airport(models.Model):
    code = models.CharField(max_length=3)
    city = models.CharField(max_length=64)

    def __str__(self):
        return f"{self.city} ({self.code})"

class Flight(models.Model):
    origin = models.ForeignKey(Airport, on_delete=models.CASCADE, related_name="departures")
    destination = models.ForeignKey(Airport, on_delete=models.CASCADE, related_name="arrivals")
    outboundDate = models.DateTimeField()
    inboundDate = models.DateTimeField(blank=True, null=True)
    userCountry = models.CharField(max_length=50, default=None)
    userCurrency = models.CharField(max_length=4)
    userLocale = models.CharField(max_length=50, default=None)
    bookingDate = models.DateTimeField()
    price = models.DecimalField(max_digits=7, decimal_places=2)

    def __str__(self):
        return f"{self.id}: {self.origin} to {self.destination}"

class Passenger(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=None)
    first = models.CharField(max_length=64)
    last = models.CharField(max_length=64)
    flights = models.ManyToManyField(Flight, blank=True, related_name="passengers")

    def __str__(self):
        return f"{self.first} {self.last}"

Final Project/finalproject/flightfinder/views.py
import json
from amadeus import Client, ResponseError, Location
from datetime import datetime
from django.core.paginator import Paginator
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.db import IntegrityError
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt

from .models import User, Airport, Flight, Passenger

amadeus = Client(client_id='iSHb849cZ8n5ogZNFs4ifWaG1ErpMp89', 
                 client_secret='5cS9MUKCzyYlBcJ3', 
                 log_level='debug') 

# Create your views here.
def index(request):
    return render(request, 'flightfinder/index.html')

def login_view(request):
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["email"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("Flightfinder:index"))
        else:
            return render(request, 'flightfinder/login.html', {
                "message": "Invalid email and/or password."
            })
    else:
        return render(request, 'flightfinder/login.html')


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("Flightfinder:index"))


def register(request):
    if request.method == "POST":
        username = request.POST["email"]
        email = request.POST["email"]


        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, 'flightfinder/register.html', {
                "message": "Passwords must match."
            })

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            return render(request, 'flightfinder/register.html', {
                "message": "Account already exists."
            })
        login(request, user)
        return HttpResponseRedirect(reverse("Flightfinder:index"))
    else:
        return render(request, 'flightfinder/register.html')

def origin_airport_search(request):
    if request.is_ajax():
        try:
            data = amadeus.reference_data.locations.get(keyword=request.GET.get('term', None), subType=Location.ANY).data
        except ResponseError as error:
            messages.add_message(request, messages.ERROR, error)
    return HttpResponse(get_city_airport_list(data), 'application/json')

def get_city_airport_list(data):
    result = []
    for i, val in enumerate(data):
        result.append(data[i]['iataCode']+', '+data[i]['name'])
    result = list(dict.fromkeys(result))
    return json.dumps(result)

def flight_search(request): 
    originFull = request.POST.get('Origin')
    originThree = originFull[:3]
    destinationFull = request.POST.get('Destination')
    destinationThree = destinationFull[:3]
    kwargs = {'originLocationCode': originThree,
            'destinationLocationCode': destinationThree, 
            'departureDate': request.POST.get('Departuredate'), 
            'returnDate': request.POST.get('Returndate'),
            'adults': '1'}
            
    try: 
        response = amadeus.shopping.flight_offers_search.get(
        **kwargs)
        data = []
        origin = request.POST.get('Origin')
        destination = request.POST.get('Destination')
        for resp in response.data:
            data.append(resp)
        # Paginate posts in groups of 10
        paginatedFlightResults = Paginator(data, 10)
        page_number = request.GET.get('page')
        page_obj = paginatedFlightResults.get_page(page_number)
        return render(request, "flightfinder/flight_search.html", {
            "data": data,
            "origin": origin,
            "destination": destination,
            "page_obj": page_obj
    })
    except ResponseError as error:
        raise error

Final Project/finalproject/flightfinder/templates/flightfinder/flight_search.html
{% extends "flightfinder/layout.html" %}

{% block body %}
{{ origin }} to {{ destination }}
<br>
  {% for flight in page_obj %}
------------Offer {{ flight.id }}------------
    {% for itinerary in flight.itineraries %}
      {% if forloop.first %}
        <div class="container border">
          <div class="row">
            <div class="col">
            </div>
            <div class="col-8 text-center">
              -----------Outbound Journey-----------
            </div>
            <div class="col">
            </div>
          </div>
        <br><br>
      {% endif %}
      {% if forloop.last %}
          <div class="row">
            <div class="col">
            </div>
            <div class="col-8 text-center">
              -----------Return Journey-----------
            </div>
            <div class="col">
            </div>
        <br><br>
      {% endif %}
      {% for segment in itinerary.segments %}
        {% if forloop.counter == 1 %}
          Flight 1
          <div class="container border">
            <div class="row">
              <div class="col-6 text-center border">
                Departing:
                <br>
                {{ segment.departure.iataCode }}
                <br>
                {{ segment.departure.at }}
              </div>
              <div class="col-6 text-center border">
                Arriving:
                <br>
                {{ segment.arrival.iataCode }}
                <br>
                {{ segment.arrival.at }}
              </div>
            </div>
            <div class="row">
              <div class="col-3 text-center border">
                Airline:
                <br>
                {{ segment.operating.carrierCode }}
              </div>
              <div class="col-3 text-center border">
                Aircraft:
                <br>
                {{ segment.aircraft.code }}
              </div>
              <div class="col-3 text-center border">
                Flight No:
                <br>
                {{ segment.number }}
              </div>
              <div class="col-3 text-center border">
                Duration: 
                <br>
                {{ segment.duration }}
              </div>
            </div>
          </div>
          <br><br>
        {% endif %}
        {% if forloop.counter == 2 %}
        Flight 2
        <div class="container border">
          <div class="row">
            <div class="col-6 text-center border">
              Departing:
              <br>
              {{ segment.departure.iataCode }}
              <br>
              {{ segment.departure.at }}
            </div>
            <div class="col-6 text-center border">
              Arriving:
              <br>
              {{ segment.arrival.iataCode }}
              <br>
              {{ segment.arrival.at }}
            </div>
          </div>
          <div class="row">
            <div class="col-3 text-center border">
              Airline:
              <br>
              {{ segment.operating.carrierCode }}
            </div>
            <div class="col-3 text-center border">
              Aircraft:
              <br>
              {{ segment.aircraft.code }}
            </div>
            <div class="col-3 text-center border">
              Flight No:
              <br>
              {{ segment.number }}
            </div>
            <div class="col-3 text-center border">
              Duration: 
              <br>
              {{ segment.duration }}
            </div>
          </div>
        </div>
        <br><br>      
        {% endif %}
      {% endfor %}
    {% endfor %}
  {{ price.total }} {{ price.currency }}
  {% endfor %}
  <div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
  </div>
{% endblock %}

Final Project/finalproject/flightfinder/templates/flightfinder/index.html
{% extends "flightfinder/layout.html" %}

{% block head %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.3/modernizr.js"></script>
{% endblock %}

{% block body %}
<div id="mainhomepagediv">
    <div class="container-fluid px-0" id="mainhomepagediv">
        <div class="row mx-0">
            <div class="col-12 px-0">
                <img src="https://i.ibb.co/rHYzcyc/Landscape2.jpg" class="img-fluid w-100">
            </div>
        </div>
    </div>
    <div>
        <h1 id="homepageh1">Where are you flying to?</h1>
        <div id="homepagebox">
            <div>
                <form action="{% url 'Flightfinder:flight_search' %}" method="POST" id="homepageform">
                  {% csrf_token %} 
                    <div class="row">
                      <div class="col">
                        <label id="homepageformlabel">From</label>
                        <input type="text" class="form-control" placeholder="Origin City" name="Origin" id="inputOrigin" required>
                      </div>
                      <div class="col pb-3">
                        <label id="homepageformlabel">To</label>
                        <input type="text" class="form-control" placeholder="Destination City" name="Destination" id="inputDestination" required>
                      </div>
                    </div>
                    <div class="row">
                        <div class="col-3">
                          <label id="homepageformlabel">Depart</label>
                          <input type="date" class="form-control" name="Departuredate" id="idDeparturedate" required>
                        </div>
                        <div class="col-3" id="returnDateDiv">
                            <label id="homepageformlabel">Return</label>
                            <input type="date" class="form-control" name="Returndate" id="idReturndate">
                        </div>
                        <div class="col-3">
                          <label id="homepageformlabel">Class</label>
                          <select id="inputState" class="form-control" required>
                            <option selected>Economy</option>
                            <option>Business</option>
                            <option>First</option>
                          </select>
                        </div>
                        <div class="col">
                          <div class="radio">
                            <label><input type="radio" name="optradio" value="false" id="returnOption" checked> Return</label>
                          </div>
                        </div>
                        <div class="col">
                          <div class="radio">
                            <label><input type="radio" name="optradio" value="true" id="oneWayOption"> One Way</label>
                          </div>
                        </div>
                      </div>
                      <div class="row">
                        <div class="col">
                        </div>
                        <div class="col-3 pt-3">
                            <button class="btn float-right" name="Submit" id="homepageformbutton" type="submit">Search flights</button>
                        </div>
                      </div>
                  </form>
            </div>
        </div>
    </div>
</div>
{% if user.is_anonymous %}
<div class="disable-outside-clicks" id="myFormDiv">
  <div class="form-popup" id="myForm">
    <form class="form-container">
      <p id="homepagePopupHeaderText">Welcome!<p>
      <p id="homepagePopupParagraphText">Please login to search for flights.</p>
      <input type="text" placeholder="Email" name="email" required>
      <input type="password" placeholder="Password" name="password" id="password" required>
      <button type="submit" class="btn">Login</button>
      <a href="#" class="close" onclick="closeForm()"></a>
      <p id="homepagePopupSignupText">Don't have an account? <a href="{% url 'Flightfinder:register' %}" id="homepagePopupSignupLink">Sign up now</a></p>
    </form>
  </div>
</div>
{% endif %}
<style>
  .ui-autocomplete {
  font-size: 14px;
  text-align: left;
  background-color: #ffffff;
  border: 1px solid #cccccc;
  border: 1px solid rgba(0, 0, 0, 0.15);
  border-radius: 4px;
  background-clip: padding-box;
}
</style>
<script>
  // Amadeus origin airport search
  $(document).ready(function () {
      $("#inputOrigin").autocomplete({
          source: "{% url 'Flightfinder:origin_airport_search' %}",
          minLength: 1,
          delay: 200,
      });
  });
    // Amadeus destination airport search
    $(document).ready(function () {
      $("#inputDestination").autocomplete({
          source: "{% url 'Flightfinder:origin_airport_search' %}",
          minLength: 1,
          delay: 200,
      });
  });
  </script>
{% endblock %}

Final Project/finalproject/flightfinder/templates/flightfinder/layout.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <!-- jQuery & jQuery UI -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/smoothness/jquery-ui.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>

    <!-- Bootstrap (includes Popper) -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Main CSS-->
    <link rel="stylesheet" type="text/css" href="{% static 'flightfinder/styles.css' %}">

    <!-- Main JS -->
    <script src="{% static 'flightfinder/main.js' %}"></script>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <!-- Font Awesome Icons -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">

    <title>{% block title %}Flight Finder{% endblock %}</title>
    {% block head %}
    {% endblock %}
  </head>
  <body>
      <nav class="navbar navbar-expand-lg navbar-light">
        <a class="navbar-brand" href="{% url 'Flightfinder:index' %}">
            <img src="https://i.ibb.co/TRBkPBZ/Flight-Finder-removebg-preview.png" width="166" height="42" class="d-inline-block align-top" alt="">
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav">
            <a class="nav-item nav-link active" href="{% url 'Flightfinder:index' %}">Flights <span class="sr-only">(current)</span></a>
            <a class="nav-item nav-link" href="#">Hotels</a>
            <a class="nav-item nav-link" href="#">Car Hire</a>
          </div>
          <div class="navbar-nav ml-auto">
            {% if user.is_authenticated %}
            <a class="nav-item nav-link" href="{% url 'Flightfinder:logout' %}">Log Out</a>
            <a class="nav-item nav-link" href="#">Account</a>
            {% else %}
            <a class="nav-item nav-link" href="{% url 'Flightfinder:login' %}">Log In</a>
            <a class="nav-item nav-link" href="{% url 'Flightfinder:register' %}">Register</a>
            {% endif %}
          </div>
        </div>
      </nav>
    {% block body %}
    {% endblock %}
  </body>
</html>

Final Project/finalproject/flightfinder/templates/flightfinder/login.html
{% extends "flightfinder/layout.html" %}

{% block body %}

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}
    
    <div id="mainLoginDiv">
        <div class="container-fluid px-0" id="mainhomepagediv">
            <div class="row mx-0">
                <div class="col-12 px-0">
                    <img src="https://i.ibb.co/rHYzcyc/Landscape2.jpg" class="img-fluid w-100">
                </div>
            </div>
        </div>
        <div>
            <h1 id="loginH1">Fly away today</h1>
            <div id="loginBox">
                <div>
                    <form action="#" method="post" id="loginForm">
                        {% csrf_token %}
                        <div class="form-group">
                            <input class="form-control" type="email" name="email" placeholder="Email Address">
                        </div>
                        <div class="form-group">
                            <input class="form-control" type="password" name="password" placeholder="Password">
                        </div>
                        <input class="btn float-right" id="loginFormButton" type="submit" value="Login"><p id="loginFormText">Don't have an account? <a href="{% url 'Flightfinder:register' %}" id="loginFormLinkText">Register here.</a></p>
                    </form>
                </div>
            </div>
        </div>
    </div>  
{% endblock %}

Final Project/finalproject/flightfinder/templates/flightfinder/register.html
{% extends "flightfinder/layout.html" %}

{% block body %}

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <div id="mainRegisterDiv">
        <div class="container-fluid px-0" id="mainhomepagediv">
            <div class="row mx-0">
                <div class="col-12 px-0">
                    <img src="https://i.ibb.co/rHYzcyc/Landscape2.jpg" class="img-fluid w-100">
                </div>
            </div>
        </div>
        <div>
            <h1 id="registerH1">Get the full experience</h1>
            <div id="registerBox">
                <div>
                    <form method="post" id="registerForm" name="registration" onsubmit="return formValidation()">
                        {% csrf_token %}
                        <div class="form-group">
                            <input class="form-control" type="email" name="email" placeholder="Email Address">
                        </div>
                        <div class="form-group">
                            <input class="form-control" type="password" name="password" placeholder="Password">
                        </div>
                        <div class="form-group">
                            <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password">
                        </div>
                        <input class="btn float-right" id="registerFormButton" type="submit" value="Register"><p id="registerFormText">Already have an account? <a href="{% url 'Flightfinder:login' %}" id="registerFormLinkText">Log In here.</a></p>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

Final Project/finalproject/flightfinder/templates/flightfinder/results.html
{% extends "flightfinder/layout.html" %}

{% block body %}
  
{% endblock %}